### ISSUE TITLE
python2.7 is not Required by tox, but it is shown that way

### ISSUE THREAD

**Issue by hroncok** [frenzymadness/RPMGraph#8]
When I enter `python2.7`, depth 1, I see:

![graph](https://github.com/frenzymadness/RPMGraph/assets/2401856/a9615aa1-2781-4e07-b79b-b044a386e19b)

This seams tox Requires python2.7, but it does not, it only Recommends that. Treating Recommends as Requires makes it impossible for me to explore the python2.7 dependency graph beyond depth level 1, because it is too big (and incorrect).

**Comment by hroncok** [comment]
In another tool of mine, I solved this by setting ignore_weak_deps=False when resolving a dnf transaction:

https://github.com/hroncok/whatdoibuild/blob/1413be51b0952d8c0a2e295c53f721067654099e/resolve_buildroot.py#L94

**Comment by frenzymadness** [comment]
Thanks for the great idea.

> ignore_weak_deps=False

I guess it should be `True` or is the logic reversed?

**Comment by hroncok** [comment]
Yeah, I mean True, sorry.
